# Site settings
title: Udit Malik # site title
description: >- # site description
  A personal website for Udit Malik. GitHub: 
    <a href="https://github.com/malikudit" target="_blank" rel="noopener">@malikudit</a>.
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/malikudit/malikudit.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Udit Malik # author name
  bio: >- # tell to the world
    Hello! I'm a junior at Vanderbilt University, majoring in CS, and an incoming Data Scientist Intern at Meta! 
    Check out my <a href="https://github.com/malikudit" target="_blank" rel="noopener">@GitHub,</a>
    <a href="https://linkedin.com/in/udit-malik" target="_blank" rel="noopener">@LinkedIn,</a> or
    <a href="https://malikudit.github.io" target="_blank" rel="noopener">@Resume.</a>
  username: malikudit # author username
  github: malikudit
  twitter: uditttttt
  facebook: uditnow
  email: udit.malik@vanderbilt.edu
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://malikudit.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
